# Generated by Django 4.2 on 2024-07-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('genre', models.CharField(max_length=25)),
                ('director', models.CharField(max_length=40)),
                ('year', models.IntegerField()),
                ('sinopsis', models.TextField()),
            ],
        ),
    ]
